import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  content: { padding: 20 },
  title: { fontSize: 32, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  subtitle: { fontSize: 16, color: '#666', marginBottom: 24 },
  optionCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  optionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  optionTitle: { fontSize: 18, fontWeight: '600', color: '#333', marginBottom: 8 },
  optionDescription: { fontSize: 14, color: '#666', lineHeight: 20 },
  periodButtons: { flexDirection: 'row', gap: 12, marginTop: 12 },
  periodButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    alignItems: 'center',
  },
  periodButtonActive: { backgroundColor: '#34C759', borderColor: '#34C759' },
  periodButtonText: { fontSize: 14, color: '#666', fontWeight: '500', textAlign: 'center' },
  periodButtonTextActive: { color: '#fff' },
  generateButton: {
    backgroundColor: '#007AFF',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  buttonDisabled: { opacity: 0.6 },
  generateButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  loadingContainer: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  loadingText: { color: '#fff', fontSize: 16, marginLeft: 10 },
  cacheButton: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  cacheButtonText: { color: '#666', fontSize: 14, fontWeight: '600' },
  planPreview: {
    backgroundColor: '#e8f5e9',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
  },
  planTitle: { fontSize: 18, fontWeight: '600', color: '#2e7d32', marginBottom: 8 },
  planText: { fontSize: 16, color: '#1b5e20', lineHeight: 22, marginBottom: 4 },
  planSubtext: { fontSize: 14, color: '#2e7d32', lineHeight: 20, marginTop: 8, fontStyle: 'italic' },
});
