import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  content: { padding: 20, paddingBottom: 40 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 10, color: '#666', fontSize: 16 },
  
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: { fontSize: 28, fontWeight: 'bold', color: '#333' },
  todayButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  todayButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  
  dateNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  dateButton: { padding: 8 },
  dateButtonText: { fontSize: 14, color: '#007AFF', fontWeight: '600' },
  dateContainer: { alignItems: 'center' },
  dateText: { fontSize: 16, color: '#333', fontWeight: '600', textTransform: 'capitalize' },
  todayBadge: { fontSize: 12, color: '#34C759', fontWeight: '600', marginTop: 4 },
  
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  summaryTitle: { fontSize: 16, fontWeight: '600', color: '#666', marginBottom: 8 },
  summaryText: { fontSize: 28, fontWeight: 'bold', color: '#34C759', marginBottom: 12 },
  progressBar: { height: 12, backgroundColor: '#e0e0e0', borderRadius: 6, overflow: 'hidden', marginBottom: 8 },
  progressFill: { height: '100%', backgroundColor: '#34C759', borderRadius: 6 },
  summarySubtext: { fontSize: 14, color: '#666' },
  
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  
  emptyState: { alignItems: 'center', paddingVertical: 80 },
  emptyIcon: { fontSize: 80, marginBottom: 20 },
  emptyTitle: { fontSize: 20, fontWeight: '600', color: '#333', marginBottom: 12, textAlign: 'center', paddingHorizontal: 20 },
  emptyText: { fontSize: 15, color: '#666', textAlign: 'center', paddingHorizontal: 30, lineHeight: 22 },
  emptyTextBold: { fontWeight: '700', color: '#007AFF' },
  
  mealCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  mealHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  mealType: { fontSize: 14, fontWeight: '600', color: '#007AFF', marginBottom: 4 },
  mealName: { fontSize: 18, fontWeight: 'bold', color: '#333', maxWidth: 250 },
  checkbox: { padding: 8 },
  checkboxChecked: { backgroundColor: '#e8f5e9', borderRadius: 8 },
  checkboxText: { fontSize: 28 },
  
  macros: { 
    flexDirection: 'row', 
    justifyContent: 'space-around',
    backgroundColor: '#f8f9fa',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  macroItem: { alignItems: 'center' },
  macroValue: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 2 },
  macroLabel: { fontSize: 11, color: '#666', textTransform: 'uppercase' },
  
  ingredients: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
  ingredientsTitle: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 8 },
  ingredientItem: { fontSize: 14, color: '#666', marginBottom: 4, lineHeight: 20 },
  
  instructions: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
  instructionsTitle: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 8 },
  instructionsText: { fontSize: 14, color: '#666', lineHeight: 20 },
});
