# Versão do Docker Compose
version: '3.8'

# Definimos aqui os nossos contêineres (serviços)
services:

  # 1. Serviço da nossa API
  api:
    build: .
    # --- CORRIGIDO --- Nome do contêiner atualizado
    container_name: smarteat-api-service-mobile
    ports:
      - "4000:4000"
    environment:
      # --- CORRIGIDO --- Credenciais alinhadas com o serviço 'db'
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_DATABASE=smarteat
      - DB_PORT=5432
    depends_on:
      - db

  # 2. Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    # --- CORRIGIDO --- Nome do contêiner atualizado
    container_name: smarteat-db-service-mobile
    restart: always
    # As credenciais que o banco de dados usará na inicialização
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=smarteat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volume para persistir os dados do banco
volumes:
  postgres_data: